Fixes #1
allejo/php-vcr-sanitizer pull request #2
Opened 2018-09-05 08:49 UTC by janvernieuwe

Add body scrubber

2018-09-05 15:30 UTC, allejo requested changes

2018-09-05 15:30 UTC, allejo commented on src/VCRCleanerEventSubscriber.php
> +        foreach ($options['bodyScrubber'] as $scubber) {
should be `$scrubber`

2018-09-05 15:30 UTC, allejo commented on src/RelaxedRequestMatcher.php
> +                'bodyScrubber'        => array(),
Since this accepts an array of body scrubbers, I'd opt towards naming it `bodyScrubbers` throughout the classes instead.

2018-09-05 15:30 UTC, allejo commented on tests/VCR/RelaxedRequestMatcherTest.php
> +                'bodyScrubber' => function ($body) {
`RelaxedRequestMatcher::configureOptions()` takes `bodyScrubber` as an array, no? Shouldn't this be an array of functions instead?

2018-09-05 15:30 UTC, allejo commented on tests/VCR/VCRCleanerEventSubscriberTest.php
> +            'bodyScrubber' => function($body) {
Same as other comment on other unit test

2018-09-05 21:03 UTC, allejo requested changes

2018-09-05 21:03 UTC, allejo commented on README.md
> +    })
Trailing comma on here, please.

2018-09-05 21:03 UTC, allejo commented
Would you mind writing a 'Using Body Scrubbers' section after the [Hiding URL Parameters](https://github.com/allejo/php-vcr-sanitizer#hiding-url-parameters) section demonstrating its purpose?

After that, this looks good to me!

2018-09-05 21:04 UTC, janvernieuwe commented
Alright, will do thanks for your time in reviewing

2018-09-06 02:44 UTC, allejo approved these changes

2018-09-06 02:59 UTC, allejo commented
Thank you for all your work on this feature and making the requested changes! 🎉

I've merged your changes in manually in 021c92e1eedd5ad8751da849a7f14f2ab5d03e79 instead of through GitHub just so I could clean the commit history a bit. But don't worry, you still get full credit for all the changes in your commits and in git blame.

- 0bbec32e746500e708e6e1e3ef3b062667986bbb
- bb935799205b8cf12dbb148c44790fbe7d461bed
- fd0c32e5b1953028bfeff4ff5fd72dadb0c2e802

2018-09-06 02:59 UTC, closed without merging

2018-09-06 06:01 UTC, janvernieuwe commented
np, just wondering though, didn't github's squash commits on merge work?

2018-09-06 06:08 UTC, allejo commented
Yea, squashing the commits would have worked just fine too. I just opted not to do that in this particular case because I wanted to split up your commits a bit more instead of just combing them all into one. Just personal taste, no technical reason at all 🤷‍♂️